### ISSUE TITLE
Some drawings cannot be rendered

### ISSUE THREAD

**Issue by laingsimon** [laingsimon/render-drawing#5]
Error appears with message:

```
Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
```

This is from a URL file which contains a `<mxfile>` element, maybe the data (element content) needs to be extracted from the response and passed along?

The samples contain a file which is returned in this format and works without issue, it could be a deflate/inflate versioning issue?

**Comment by ghost** [comment]
Resolved by extracting the diagram compressed content from returned data
